version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db-vlearn
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vlearn
    ports:
      - "5458:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
